# Generated by Django 6.0.6 on 2026-07-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_items_guest_name_items_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
