# Generated by Django 6.0.6 on 2026-07-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='guest_phone',
        ),
        migrations.CreateModel(
            name='ItemReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='mysite.items')),
            ],
        ),
    ]
