# Generated by Django 6.0.6 on 2026-07-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_items_guest_name_remove_items_guest_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
    ]
