# Generated by Django 6.0.6 on 2026-07-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_items_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
