# Generated by Django 6.0.6 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_item_alter_itemreservation_item_delete_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='item',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Foto 1'),
        ),
    ]
